baseURL = "/"
title = "Floopr, The Free Loop Libary"
paginate = 8

[taxonomies]
  key = "key"
  authors = "authors"
  tempo = "tempo"
  type = "type"
  timesig = "timesig"

[sitemap]
  filename = 'sitemap.xml'
  priority = 0.5
