baseURL = "/"
title = "Floopr"
paginate = 6

[taxonomies]
  key = "key"
  author = "author"
  tempo = "tempo"
  type = "type"
  timesig = "timesig"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20
  [[menu.main]]
    identifier = "loops"
    name = "Loops"
    url = "/loops"
    weight = 30
  [[menu.main]]
    identifier = "terms"
    name = "Terms of use"
    url = "/terms"
    weight = 40
  [[menu.main]]
    identifier = "contribute"
    name = "Contribute"
    url = "/contribute"
    weight = 40