baseURL = "/"
title = "Floopr"
paginate = 6

[taxonomies]
  key = "keys"
  author = "authors"
  tempo = "tempos"
  type = "types"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20
  [[menu.main]]
    identifier = "loops"
    name = "Loops"
    url = "/loops"
    weight = 30
  [[menu.main]]
    identifier = "contribute"
    name = "Contribute"
    url = "/contribute"
    weight = 40