name: Deploy frontend to Edgeserver.IO

on:
  push:
    branches:
      - "main"

jobs:
  dostuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.92.2'
          extended: true
      - name: Build
        run: hugo -gc --minify
      - name: "Delete stuff"
      - run: rm -r public/static/audio
      - name: Edgeserver Upload
        uses: lvkdotsh/edgeserver-action@master
        with:
          app_id: "987654333"
          server: https://api.edgeserver.io
          token: ${{ secrets.EDGETOKEN }}
          directory: public