name: Deploy frontend to Edgeserver.IO

on:
  push:
    branches:
      - "main"

jobs:
  dostuff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: jakejarvis/hugo-build-action@master
        with:
          args: --minify --gc
      - run: sudo rm -r public/audio
      - name: Edgeserver Upload
        uses: lvkdotsh/edgeserver-action@master
        with:
          app_id: "987654333"
          server: https://api.edgeserver.io
          token: ${{ secrets.EDGETOKEN }}
          directory: public