name: Deploy frontend to Edgeserver.IO

on:
  push:
    branches:
      - "main"

jobs:
  dostuff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: rm -r public/loops/
      - uses: actions/setup-node@v2
        with:
          node-version: "19.1.0"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - name: Build
        run: yarn build
      - name: Edgeserver Upload
        uses: lvkdotsh/edgeserver-action@master
        with:
          app_id: "118663342767214592"
          server: https://api.edgeserver.io
          token: ${{ secrets.EDGETOKEN }}
          directory: dist
